### ISSUE TITLE
LGTM alert "Instantiating an exception, but not raising it, has no effect"

### ISSUE THREAD

**Issue by vytas7** [Jithinqw/Camembert#8]
https://lgtm.com/projects/g/Jithinqw/Camembert/alerts/?mode=list

In `camembert/response_setter.py`
```python
        else:
            falcon.HTTPBadRequest(
                title="Bad Request",
                description="Response headers should be a dictonary.",
            )
```

Probably better off as :arrow_right: `raise falcon.HTTPBadRequest(...`

**Comment by Jithinqw** [comment]
Hai @vytas7  thank you for your issue. Working on this now.

**Comment by Jithinqw** [comment]
Fixed on the latest commit
